version: 0.1
phases:
  install:
    commands:
      - pwd && cd v1 && npm install time
      - aws cloudformation package --template-file v1/samTemplate.yaml --s3-bucket test-sam2 --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml

