version: 0.1
phases:
  install:
    commands:
      - pwd && cd v1 && npm install time
      - pwd && cd v1 && aws cloudformation package --template-file samTemplate.yaml --s3-bucket test-sam2 --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - v1/NewSamTemplate.yaml

