AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time

Parameters:
    Var1:
        Type: String
    Var2:
        Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: sandbox
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/time":
                get:
                  x-amazon-apigateway-integration:
                    credentials: "arn:aws:iam::462029873890:role/Swagger-Lambda-Role"
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
                  responses: {}
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      AutoPublishAlias: live
      Environment:
        Variables:
          var1: !Ref Var1
          var2: !Ref Var2

