swagger: "2.0"
info:
  title: "MyBetaStack2"
schemes:
- https
paths:
  "v1/time":
     get:
       x-amazon-apigateway-integration:
         credentials: "arn:aws:iam::462029873890:role/Swagger-Lambda-Role"
         httpMethod: POST
         type: aws_proxy
         uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:462029873890:function:${stageVariables.LambdaFunctionNameV1}:${stageVariables.LambdaAliasV1}/invocations
       responses: {}

  "v2/time":
     get:
       x-amazon-apigateway-integration:
         credentials: "arn:aws:iam::462029873890:role/Swagger-Lambda-Role"
         httpMethod: POST
         type: aws_proxy
         uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:462029873890:function:${stageVariables.LambdaFunctionNameV2}:${stageVariables.LambdaAliasV2}/invocations
       responses: {}



