swagger: "2.0"
info:
  title: "RefAWSStackName"
schemes:
- https
paths:
  "/time":
     get:
       x-amazon-apigateway-integration:
         credentials: "arn:aws:iam::462029873890:role/Swagger-Lambda-Role"
         httpMethod: POST
         type: aws_proxy
         uri: "Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations"
       responses: {}

